language: ruby
cache: bundler
bundler_args: --without development
before_script: "bin/rake refinery:testing:dummy_app"
env:
  - DB=postgresql
  - DB=mysql
notifications:
  email: 
    - unixcharles@gmail.com
rvm:
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0.0
sudo: false